const Discord = require('discord.js');
const client = new Discord.Client();
console.log("Scrpit By Dream");

client.on("ready", () => {
let channel =     client.channels.get("509500632651005958")
setInterval(function() {
channel.send(abcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyz);
}, 25)
})
 
 
client.login('NDM2OTE4MTIwMTg0MDIxMDEy.DtGh-w.8bOVDNHZdX_hgghIq3qiw3ngBps');
